import "./globals.css";
import Nav from "@/components/Navigation";
import FinanceContextProvider from "@/lib/store/finance-context";
import AuthContextProvider from "@/lib/store/auth-context";
import { ToastContainer, toast } from "react-toastify";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container max-w-2xl px-6 py-6 mx-auto">
        <AuthContextProvider>
          <FinanceContextProvider>
              <Nav />
              {children}
            <ToastContainer/>
          </FinanceContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
